spring:
  data:
     redis:
       host: localhost
       port: 6379 # Redis ??
       password: # Redis ????????????????
       database: 0 # Redis ????????? 0?
       timeout: 3000 # ?????????????
       lettuce:
         pool:
           max-active: 8 # ????????? 8?
           max-idle: 8 # ??????????? 8?
           min-idle: 0 # ??????????? 0?
           max-wait: 1000 # ??????????????????-1 ???????


